"""aggregate snapshot schema

Revision ID: 169ed8e45f02
Revises: 
Create Date: 2026-08-10 14:10:56.347610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169ed8e45f02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('change_from_last_month_percent', sa.Float(), nullable=False),
    sa.Column('normal_attendance_count', sa.Integer(), nullable=False),
    sa.Column('normal_attendance_percent', sa.Float(), nullable=False),
    sa.Column('abnormal_attendance_count', sa.Integer(), nullable=False),
    sa.Column('abnormal_attendance_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('on_time_count', sa.Float(), nullable=False),
    sa.Column('on_time_percent', sa.Float(), nullable=False),
    sa.Column('late_count', sa.Float(), nullable=False),
    sa.Column('late_percent', sa.Float(), nullable=False),
    sa.Column('leave_count', sa.Float(), nullable=False),
    sa.Column('leave_percent', sa.Float(), nullable=False),
    sa.Column('absent_count', sa.Float(), nullable=False),
    sa.Column('absent_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_status_snapshot_id'), 'attendance_status', ['snapshot_id'], unique=True)
    op.create_table('gender_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('female_count', sa.Integer(), nullable=False),
    sa.Column('female_percent', sa.Float(), nullable=False),
    sa.Column('male_count', sa.Integer(), nullable=False),
    sa.Column('male_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gender_distribution_snapshot_id'), 'gender_distribution', ['snapshot_id'], unique=True)
    op.create_table('grade_level_breakdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('normal', sa.Integer(), nullable=False),
    sa.Column('absent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_level_breakdown_snapshot_id'), 'grade_level_breakdown', ['snapshot_id'], unique=False)
    op.create_table('monthly_attendance_trend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('attendance_percent', sa.Float(), nullable=False),
    sa.Column('absent_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_attendance_trend_snapshot_id'), 'monthly_attendance_trend', ['snapshot_id'], unique=False)
    op.create_table('streams_breakdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('science_count', sa.Integer(), nullable=False),
    sa.Column('science_percent', sa.Float(), nullable=False),
    sa.Column('social_science_count', sa.Integer(), nullable=False),
    sa.Column('social_science_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_breakdown_snapshot_id'), 'streams_breakdown', ['snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streams_breakdown_snapshot_id'), table_name='streams_breakdown')
    op.drop_table('streams_breakdown')
    op.drop_index(op.f('ix_monthly_attendance_trend_snapshot_id'), table_name='monthly_attendance_trend')
    op.drop_table('monthly_attendance_trend')
    op.drop_index(op.f('ix_grade_level_breakdown_snapshot_id'), table_name='grade_level_breakdown')
    op.drop_table('grade_level_breakdown')
    op.drop_index(op.f('ix_gender_distribution_snapshot_id'), table_name='gender_distribution')
    op.drop_table('gender_distribution')
    op.drop_index(op.f('ix_attendance_status_snapshot_id'), table_name='attendance_status')
    op.drop_table('attendance_status')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
