"""drop derived percent/absent columns

Revision ID: 874a757381d1
Revises: 889a29fb14d8
Create Date: 2026-08-13 14:18:05.148221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874a757381d1'
down_revision: Union[str, Sequence[str], None] = '889a29fb14d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_status', sa.Column('on_time_percent', sa.Float(), nullable=False))
    op.add_column('attendance_status', sa.Column('late_percent', sa.Float(), nullable=False))
    op.add_column('attendance_status', sa.Column('leave_percent', sa.Float(), nullable=False))
    op.add_column('attendance_status', sa.Column('absent_percent', sa.Float(), nullable=False))
    op.add_column('gender_distribution', sa.Column('female_percent', sa.Float(), nullable=False))
    op.add_column('gender_distribution', sa.Column('male_percent', sa.Float(), nullable=False))
    op.add_column('grade_level_breakdown', sa.Column('absent', sa.Integer(), nullable=False))
    op.add_column('monthly_attendance_trend', sa.Column('absent_percent', sa.Float(), nullable=False))
    op.add_column('streams_breakdown', sa.Column('science_percent', sa.Float(), nullable=False))
    op.add_column('streams_breakdown', sa.Column('social_science_percent', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams_breakdown', 'social_science_percent')
    op.drop_column('streams_breakdown', 'science_percent')
    op.drop_column('monthly_attendance_trend', 'absent_percent')
    op.drop_column('grade_level_breakdown', 'absent')
    op.drop_column('gender_distribution', 'male_percent')
    op.drop_column('gender_distribution', 'female_percent')
    op.drop_column('attendance_status', 'absent_percent')
    op.drop_column('attendance_status', 'leave_percent')
    op.drop_column('attendance_status', 'late_percent')
    op.drop_column('attendance_status', 'on_time_percent')
    # ### end Alembic commands ###
